---
title: "Patient-Specific Effects of Medication Using Latent Force Models with Gaussian Processes"
author: "Kaiqian Zhang"
date: "6/7/2019"
output: 
  workflowr::wflow_html:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Keywords

- Hierarchical model

- Gaussian process

- Latent force model

- Causal kernel

## Innovation/problem

- Developed a framework using latent force models (LFMs) to capture **treatment effects** on patients’ physiological state estimated using medical time series data. 

- Two contributions:

    * the latent force model convolution;
    
    * the associated causal kernel.

## Method

- Use latenet force functions sampled from Gaussian processes with causal kernels.

- In particular, in order to model treatment effect, use latent force model to model mean function $\mu_{i,j}$.

- Also introduce causality by designing the GP kernel as a causal kernel.

## Comparison

- Comparison metric: MAE

    (i) Univariate GPs with a constant mean function and the baseline (squared exponential and periodic);

    (ii) Univariate GPs with an exponential decay mean function and the OU (Ornstein-Uhlenbeck) kernel;

    (iii) Matern-3/2 kernel with a second-order LTI filter for effect modeling. 

## Useful facts/tools

- Functions generated by a GP with an SE (squared exponential) kernel are smooth because SE kernel is infinitely differentiable. 

- Use predictive trajectories to demonstrate model flexibility.


