---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
---

Welcome to my research website.

This is my website for notes on paper reading. 



## Reading with Mengjie on deep learning

* Please click on [Basset: learning the regulartory code of the accessible genome with deep convolutional neural networks](basset.html) to see notes.

* Please click on [Basenji: Sequential regulatory activity prediction across chromosomes with convolutional neural networks](basenji.html) to see notes.

* Please click on [DeepVariant: A universal SNP and small-indel variant caller using deep neural networks](DeepVariant.html) to see notes.



## QCB 515 paper reading

* Please click on [Mutations of bacteria from virus sensitivity to virus resistance](bacteria-mutation.html) to see notes.

* Please click on [Metastasis results from preexisting variant cells within a malignant tumor](metastasis-results.html) to see notes.

* Please click on [Enzyme induction as an all-or-none phenomenon](induction.html) to see notes.

* Please click on [Optimality and evolutionary tuning of the expression level of a protein](optimality.html) to see notes.

* Please click on [Stochastic gene expression in a single cell](stochastic.html) to see notes.

* Please click on [Noise in gene expression determines cell fate in Bacillus subtilis](noise-fate.html) to see notes.

* Please click on [An amplified sensitivity arising from covalent modification in biological systems](ultrasensitivity.html) to see notes.

* Please click on [Robustness in simple biochemical networks](robustness.html) to see notes.

* Please click on [Robustness in bacterial chemotaxis](robustness2.html) to see notes.

* Please click on [Feature selection and dimension reduction for single cell RNA-seq based on a multinomial model](glm-pca-rnaseq.html) to see notes. 

* Please click on [Using mathematical models to help understand biological pattern formation](turing-model.html) to see notes.

* Please click on [Identification of common molecular subsequences (Smith-Waterman Algorithm) (QCB 515 paper 14)](QCBpaper14.html) to see notes.

* Please click on [Evolutionary Trees from DNA Sequences: A Maximum Likelihood Approach (QCB 515 paper 15)](QCBpaper15.html) to see notes.

* Please click on [Cluster analysis and display of genome-wide expression patterns (QCB 515 paper 16)](QCBpaper16.html) to see notes. 

* Please click on [PGC-1α-responsive genes involved in oxidative phosphorylation are coordinately downregulated in human diabetes (QCB 515 paper 17)](QCBpaper17.html) to see notes.

* Please click on [Evolutionary information for specifying a protein fold (QCB 515 paper 18)](QCBpaper18.html) to see notes. 



* Please click on [Protein sectors: evolutionary units of three-dimensional structure (QCB 515 paper 19)](QCBpaper19.html) to see notes.




## Barbara Engelhardt paper reading

* Please click on [PG-TS: Improved Thompson Sampling for Logistic Contextual Bandits (Barbara 4)](barbara4.html) to see notes.

* Please click on [Patient-Specific Effects of Medication Using Latent Force Models with Gaussian Processes (Barbara 5)](barbara5.html) to see notes. 





## John Storey paper reading

* Please click on [The optimal discovery procedure for significance analysis of general gene expression studies (John 1)](john1.html) to see notes.












