---
title: "Optimality and evolutionary tuning of the expression level of a protein"
author: "Kaiqian Zhang"
date: "3/27/2019"
header-includes:
   - \usepackage{amsmath}
output: 
  workflowr::wflow_html:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Problem

They are trying to figure out for each lactose environment, if there exists an optimal lac protein expression level that maximizes growth rate. They model the fitness by quantify growth burden and growth advantage, where they call cost and benefit. 

## Experiments

- "Dilution evolution experiments": 

- Steps for cost and benefit: 

    - experiemnt measurements 

    - formulate functions to predict

    - compare experiment measurements with predictions
    
- Measure cost: 

    - At different concentration of IPTG, which induces lac system but no benefit is gained since IPTG is not metabolized.
    
    - Cost function is nonlinear and concave. increase in lac protein expression level, increase in cost.
    

- Measure benefit:

    - At saturation IPTG for full induction, and at various concentration of sugar lactose.
    
    - Growth rate increases with lactose concentration, indicating that benefit gained by the action of the Lac proteins that transport and use this sugar.
    
    
## Findings

- The optimal protein level increases with the lactose level in the environment.

- Changes in LacZ activity are proportional to changes in LacZ protein level.

- Lactose level remains constant over most of exponential growth.

- Protein expression in evolved cells relative to wild-type cells = relative change in lactose activity.


## Simulation

- The mutants eventually take over the population. The average LacZ expression of the population therefore approaches the expression level of the mutant.









## Details

- experiment condition: constnat lactose environment

### Experiment 1

- measure cost and benefit of Lac protein expression in wild-type E. coli.

#### Cost

- define cost: reduction in growth rate due to cell production and presence of Lac protein burden

- measure cost: no lactose; at various concentration of inducer IPTG; 

- finding: the cost per protein increases as more Lac protein is produced.

#### Benefit

- define benefit: gained by the action of the Lac proteins that transport and use lactose

- measure benefit: at various concentration of lactose; full induction with saturating IPTG (to keep cost constant)

### Experiment 2

- Over generations, would E. coli actually evolve to these optimal expression levels under a constant lactose environment?

#### findings

- changes in LacZ activity were proportional to changes in LacZ protein level.

## Resource

Youtube video for operon: https://www.youtube.com/watch?v=10YWgqmAEsQ



