---
title: "Stochastic gene expression in a single cell"
author: "Kaiqian Zhang"
date: "4/1/2019"
header-includes:
   - \usepackage{amsmath}
output: 
  workflowr::wflow_html:
    code_folding: hide
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Main

Noise in gene expression usually causes cell-cell variation. Noise has two components: intrinsic and extrinsic noise. These noise can be transcription rate, regulatory dynamics, and genetic factors. The paper established a quantitative foundation for modeling noise in genetic network.  

## Definition

- `plasmid`: A plasmid is a small DNA molecule within a cell that is physically separated from chromosomal DNA and can replicate independently. 

- `lacI`: a repressor gene. lactose operon repressor; negative regulation of transcription

- `IPTG`: binds and inactivates the lac repressor.

- `Repressilator`: synthetic oscillatory network. It causes periodic synthesis of LacI, which repeatedly turns both promoters on and off. 

- `recA`: a gene. Lack of this gene will increase noise. 

- `CFP` or `YFP`: two reporter genes.

## Experiment 

- experiment process: build E coli with two fluorecent genes (construct plasmids with CFP or YFP), cells were grwon in LB medium, photographed, computer performed image analysis and quantify fluorescent intensities. Calculate noise by their definition using intensities (in Supplements). 

plot CFP and YFP intensities and then obtain noise orthogonally as in Figure 3A (how to measure noise).

- `lacI-` strain: low noise levels. 
    
    * similar results in another strain incorporating two copies of somewhat stronger promoters.
    
    * low noise state does not strictly depend on a particular promoter sequence.
    
- `lacI+` or `WT` strain: high noise level, increase by a factor of 5

- `WT` + `IPTG`: decrease the noise level, indicating the effect is reversible. 

- Because of this reversibility, we can conclude that the noise increase found in `WT` strains can be attributed diretly to the activity of LacI and the corresponding reduction in transcription rate. 

- fact: fluorecsent intensity is proportional to average number of transcripts

- `lacI-` + `Repressilator`: substantial increase in intrinsic noise and total noise
    
    * to understand the interplay between regulatory dynamics and noise
    
    * conclude that regulatory dynamics can cause substantial changes in noise level
    
- anything with `delta recA` will increase noise. What does `delta recA` mean? without recA gene??


    

    
    



















## Goal

Since the amount of protein produced by a particular gene varies from cell to cell, there exists stochastic gene expression in a single cell. 

- extrinsic noise: concentrations, states, locations of molecules, fluctuations.

- intrinsic noise: random microscopic events that govern which reactions occur and in what order. From biochemical process of gene expression.


## Findings

- No matter how accurately the levels of regulatory proteins are controlled, intrinsic noise fundamentally limits the precision of gene regulation.

- least noisy gene expression condition: strong constitutive promoters driving the expression of stable proteins

- In the lac- and other stronger promoter environment, we obtained same results (low noise state). This indicates that gene expression can be uniform under some conditions, and the low noise state does not strictly depend on a particular promoter sequence.

- Experiments in environment 1, 2, and 3 indicate that as the activity of lacI increases -> reduction of transcription rate -> increase noise.

- Extrinsic noise reaches the maximum at intermediate rates of transcription.

- Extrinsic noise is smaller in cells carrying a chromosomal copy of lacI than it is in cells carrying a plasmid-borne copy of the gene.

- delete RecA in the gene -> increase noise, increased noise may arise from transient copy-number differences between different parts of chromosome. 



## Experiments

- define intrinsic noise: the extent to which the activities of two identical copies of that gene, in the same intracellular environment, fail to correlate. 

- use strains of E. coli. colored by cyan and green

- two reporter genes were controlled by the same promoters

- measure: mean fluorescent intensities. See Fig 3. to know how to obtain intrinsic and extrinsic noise from fluorescent intensities. [Q: why are intrinsic and extrinsic noise in those directions?]

- environment 1: lac- (i.e. lacI, the lac repressor gene, is deleted) -> low intrinsic noise and low total noise

- environment 2: lac+ (i.e. wild-type) -> increase noise

- environment 3: lac+ and IPTG, which inactives the lac repressor -> low noise same as environment 1

- use Repressilator, which causes periodic synthesis of lacI, to find that regulatory dynamics can cause substantial changes in noise levels.

- delete recA in the gene -> increase noise 

## Supplementary

not fully understand...

